// Single source for the tool description, the command catalog, the no-args
// home overview, the root --help, and the generated SKILL.md (AXI principle
// 7). Edit here; skills/instantly-axi/SKILL.md is regenerated by
// `npm run skill:gen` and CI fails if it drifts (`npm run skill:check`).

import { homedir } from "node:os";
import { emitList, emitBlock } from "../output/toon.js";
import { helpBlock } from "../output/suggest.js";

export const DESCRIPTION =
  "Inspect and manage Instantly.ai cold-email campaigns, leads, and sending accounts from the terminal";

export const SPEC_VERSION = "axi/1.0-2026-07";

/** The full command surface, as one source for help, home, and SKILL.md. */
export interface CommandDoc {
  command: string;
  summary: string;
  /** Send-triggering or destructive: requires --confirm to execute. */
  gated: boolean;
}

export const COMMANDS: CommandDoc[] = [
  { command: "campaigns", summary: "List campaigns (--status active|paused|draft|completed)", gated: false },
  { command: "campaign <id>", summary: "Show a campaign's status, schedule, and sequence steps", gated: false },
  { command: "campaign launch <id>", summary: "Activate a campaign - starts sending live email", gated: true },
  { command: "campaign pause <id>", summary: "Pause a campaign (reversible)", gated: false },
  { command: "leads --campaign <id>|--list <id>", summary: "List leads in a campaign or list", gated: false },
  { command: "lead add --campaign <id> --email <email>", summary: "Add a lead", gated: true },
  { command: "lead rm <id>", summary: "Delete a lead permanently", gated: true },
  { command: "accounts", summary: "List sending accounts with health and warmup status", gated: false },
  { command: "analytics <campaign-id>", summary: "Opens, replies, bounces, and rates for a campaign", gated: false },
  { command: "verify <email>", summary: "Verify an email address - consumes credits", gated: true },
  { command: "webhooks", summary: "List configured webhooks", gated: false },
  { command: "webhooks add <url> --events <event>", summary: "Create a webhook", gated: true },
  { command: "webhooks rm <id>", summary: "Delete a webhook", gated: true },
];

export function collapseHome(path: string): string {
  const home = homedir();
  return path.startsWith(home) ? "~" + path.slice(home.length) : path;
}

/**
 * Command catalog as a TOON list. The `command` column holds the bare
 * subcommand (no tool prefix) so tooling can discover subcommands from the
 * first token; the invocation prefix is stated separately.
 */
function commandTable(): string {
  return emitList(
    "commands",
    COMMANDS.map((c) => ({
      command: c.command,
      gated: c.gated ? "yes (--confirm)" : "no",
      summary: c.summary,
    })),
    ["command", "gated", "summary"],
  );
}

/**
 * The no-credentials home / SKILL body: a compact overview of what the tool
 * does, the safety model, and how to authenticate. Pure and deterministic.
 * `tool` is how commands are invoked ("instantly-axi" or "npx -y instantly-axi").
 */
export function overview(tool: string): string {
  const runNote = `run: prefix each command with ${tool} (e.g. ${tool} campaigns)`;
  const table = commandTable();
  const safety = emitBlock("safety", [
    "Commands marked gated=yes never call the API without --confirm.",
    "Without --confirm they print a dry-run plan (method, endpoint, payload) and exit 0.",
    "Gated actions send live email, spend credits, or delete data.",
  ]);
  const next = helpBlock([
    `${tool} campaigns --status active`,
    `${tool} accounts`,
    `${tool} campaign <id>`,
    `${tool} campaign launch <id> --confirm`,
  ]);
  const auth = emitBlock("auth", [
    "Set INSTANTLY_API_KEY, or write the key to ~/.config/instantly-axi/credentials.",
    "Create a key at https://app.instantly.ai/app/settings/integrations",
  ]);
  return [runNote, table, safety, next, auth].join("\n");
}

/** Root --help: catalog plus global flags. */
export function rootHelpText(): string {
  const flags = emitList(
    "flags",
    [
      { flag: "--help", default: "", description: "show help for any command" },
      { flag: "--version", default: "", description: "print the tool version" },
    ],
    ["flag", "default", "description"],
  );
  return [
    `instantly-axi: ${DESCRIPTION} (AXI spec ${SPEC_VERSION})`,
    "run: prefix each command with instantly-axi (e.g. instantly-axi campaigns)",
    commandTable(),
    flags,
    emitBlock("examples", [
      "instantly-axi campaigns --status active",
      "instantly-axi campaign launch <id> --confirm",
    ]),
  ].join("\n");
}

/** The static SKILL.md: overview with zero-install command forms. */
export function renderSkill(): string {
  const frontmatter = [
    "---",
    "name: instantly-axi",
    `description: "${DESCRIPTION.replace(/"/g, "'")}"`,
    "---",
  ].join("\n");
  const body = [
    "# instantly-axi",
    "",
    `${DESCRIPTION} (built against AXI spec ${SPEC_VERSION}). Run the commands below with npx - no install needed.`,
    "",
    "## Safety model (read this first)",
    "",
    "Every command that sends live email, spends credits, or deletes data is **gated**: it",
    "requires an explicit `--confirm` flag. Without `--confirm` these commands print a dry-run",
    "plan - the exact method, endpoint, and payload that *would* be sent - and make **no API",
    "call** (exit 0). A bare invocation can never send email or destroy data. Read-only",
    "commands (list/get/analytics) need no flag.",
    "",
    "Gated commands: `campaign launch`, `lead add`, `lead rm`, `verify`, `webhooks add`,",
    "`webhooks rm`. Note `campaign pause` is *not* gated (it only reduces sending).",
    "",
    "## Commands",
    "",
    "```",
    overview("npx -y instantly-axi"),
    "```",
    "",
    "## Auth",
    "",
    "Set `INSTANTLY_API_KEY` (preferred) or write the key to",
    "`~/.config/instantly-axi/credentials`. Create a key in the Instantly dashboard under",
    "Settings > Integrations. The key is never logged or echoed.",
    "",
    "Every command supports `--help`. Exit codes: 0 success/no-op, 1 error, 2 usage error.",
    "All output is TOON on stdout.",
  ].join("\n");
  return [frontmatter, "", body, ""].join("\n");
}
